site_name: Hello.NPlant
theme: readthedocs
repo_url: https://github.com/mkoertgen/hello.NPlant

pages:
- Home: index.md
- Usage: usage.md
- Configuration: configuration.md
- Examples: examples.md
- FAQ: faq.md
- Why?: why.md
