site_name: hello.nplant
repo_url: https://github.com/mkoertgen/hello.NPlant
repo_name: mkoertgen/hello.nplant

theme: # https://www.mkdocs.org/user-guide/choosing-your-theme/
  # https://squidfunk.github.io/mkdocs-material/
  name: material # mkdocs, readthedocs, ...
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  locale: en
  favicon: https://consileo.io/img/favicon-32x32.png
  # logo: assets/logo.png
  features:
    # - navigation.instant
    # - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    # - navigation.prune
    - navigation.indexes
    #- toc.follow
    #- toc.integrate
    - navigation.top
  icon:
    note: octicons/tag-16
    abstract: octicons/checklist-16
    info: octicons/info-16
    tip: octicons/squirrel-16
    success: octicons/check-16
    question: octicons/question-16
    warning: octicons/alert-16
    failure: octicons/x-circle-16
    danger: octicons/zap-16
    bug: octicons/bug-16
    example: octicons/beaker-16
    quote: octicons/quote-16

extra:
  #  homepage: https://example.com
  #  consent:
  #  title: Cookie consent
  #  description: >-
  #    We use cookies to recognize your repeated visits and preferences, as well
  #    as to measure the effectiveness of our documentation and whether users
  #    find what they're searching for. With your consent, you're helping us to
  #    make our documentation better.
  # version:
  #   provider: mike
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mkoertgen
      name: mkoertgen on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcel-k%C3%B6rtgen-26118010b/
      name: mkoertgen on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mkoertg
      name: mkoertgen on Twitter

plugins:
  # - meta
  # - social
  # - tags
  - search
  - exclude: # https://github.com/apenwarr/mkdocs-exclude
      glob:
        #- exclude/this/path/*
        - "**/template.md"
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      # regex:
      #   - '.*\.(tmp|bin|tar)$'

# extra_css:
#   - stylesheets/extra.css

markdown_extensions:
  - admonition
  # mmkdocs-material insiders-only!: https://squidfunk.github.io/mkdocs-material/reference/grids/
  #- attr_list
  #- md_in_html
  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
