name: docs
on:
  push:
    branches: [main]
    paths:
      - mkdocs.yml
      - .github/workflows/docs.yml
      - "_docs/**"
      - "docs/**"
  #--- TODO: For now also enable manual runs
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      component: docs
    secrets:
      crToken: ${{ secrets.GITHUB_TOKEN }}

  # deploy:
  #   uses: ./.github/workflows/_deploy.yml
  #   needs:
  #     - build
  #   with:
  #     version: ${{ needs.build.outputs.version }}
  #     component: docs
  #   secrets:
  #     creds: ${{ secrets.AZURE_CREDENTIALS }}

  publish: # push to gitlab / gitlab pages, cf.: https://github.com/SvanBoxel/gitlab-mirror-and-ci-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # https://github.com/SvanBoxel/gitlab-mirror-and-ci-action/issues/17
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/consileo/awesome-consileo.git"
        env:
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "mkoertgen"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} # Generate here: https://gitlab.com/-/profile/personal_access_tokens
          GITLAB_PROJECT_ID: "41186024" # https://gitlab.com/<namespace>/<repository>/edit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
