name: docs
on:
  push:
    branches: [main]
    paths:
      - mkdocs.yml
      - .github/workflows/docs.yml
      - "docs/**"
  #--- TODO: For now also enable manual runs
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "dotnet: build"
        run: dotnet run --project hello.nplant/hello.nplant.csproj
      - name: "mkdocs: gh-deploy" #  # https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages
        run: |
          pip install --user -r requirements.txt
          mkdocs gh-deploy --force
